; Auto-generated. Do not edit!


(cl:in-package traj_utils-msg)


;//! \htmlinclude RemapLocalGoalList.msg.html

(cl:defclass <RemapLocalGoalList> (roslisp-msg-protocol:ros-message)
  ((guard_drone_id
    :reader guard_drone_id
    :initarg :guard_drone_id
    :type cl:fixnum
    :initform 0)
   (assignment
    :reader assignment
    :initarg :assignment
    :type (cl:vector cl:integer)
   :initform (cl:make-array 0 :element-type 'cl:integer :initial-element 0))
   (remap_lg_pos_x
    :reader remap_lg_pos_x
    :initarg :remap_lg_pos_x
    :type (cl:vector cl:float)
   :initform (cl:make-array 0 :element-type 'cl:float :initial-element 0.0))
   (remap_lg_pos_y
    :reader remap_lg_pos_y
    :initarg :remap_lg_pos_y
    :type (cl:vector cl:float)
   :initform (cl:make-array 0 :element-type 'cl:float :initial-element 0.0))
   (remap_lg_pos_z
    :reader remap_lg_pos_z
    :initarg :remap_lg_pos_z
    :type (cl:vector cl:float)
   :initform (cl:make-array 0 :element-type 'cl:float :initial-element 0.0))
   (remap_lg_vel_x
    :reader remap_lg_vel_x
    :initarg :remap_lg_vel_x
    :type (cl:vector cl:float)
   :initform (cl:make-array 0 :element-type 'cl:float :initial-element 0.0))
   (remap_lg_vel_y
    :reader remap_lg_vel_y
    :initarg :remap_lg_vel_y
    :type (cl:vector cl:float)
   :initform (cl:make-array 0 :element-type 'cl:float :initial-element 0.0))
   (remap_lg_vel_z
    :reader remap_lg_vel_z
    :initarg :remap_lg_vel_z
    :type (cl:vector cl:float)
   :initform (cl:make-array 0 :element-type 'cl:float :initial-element 0.0)))
)

(cl:defclass RemapLocalGoalList (<RemapLocalGoalList>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <RemapLocalGoalList>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'RemapLocalGoalList)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name traj_utils-msg:<RemapLocalGoalList> is deprecated: use traj_utils-msg:RemapLocalGoalList instead.")))

(cl:ensure-generic-function 'guard_drone_id-val :lambda-list '(m))
(cl:defmethod guard_drone_id-val ((m <RemapLocalGoalList>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader traj_utils-msg:guard_drone_id-val is deprecated.  Use traj_utils-msg:guard_drone_id instead.")
  (guard_drone_id m))

(cl:ensure-generic-function 'assignment-val :lambda-list '(m))
(cl:defmethod assignment-val ((m <RemapLocalGoalList>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader traj_utils-msg:assignment-val is deprecated.  Use traj_utils-msg:assignment instead.")
  (assignment m))

(cl:ensure-generic-function 'remap_lg_pos_x-val :lambda-list '(m))
(cl:defmethod remap_lg_pos_x-val ((m <RemapLocalGoalList>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader traj_utils-msg:remap_lg_pos_x-val is deprecated.  Use traj_utils-msg:remap_lg_pos_x instead.")
  (remap_lg_pos_x m))

(cl:ensure-generic-function 'remap_lg_pos_y-val :lambda-list '(m))
(cl:defmethod remap_lg_pos_y-val ((m <RemapLocalGoalList>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader traj_utils-msg:remap_lg_pos_y-val is deprecated.  Use traj_utils-msg:remap_lg_pos_y instead.")
  (remap_lg_pos_y m))

(cl:ensure-generic-function 'remap_lg_pos_z-val :lambda-list '(m))
(cl:defmethod remap_lg_pos_z-val ((m <RemapLocalGoalList>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader traj_utils-msg:remap_lg_pos_z-val is deprecated.  Use traj_utils-msg:remap_lg_pos_z instead.")
  (remap_lg_pos_z m))

(cl:ensure-generic-function 'remap_lg_vel_x-val :lambda-list '(m))
(cl:defmethod remap_lg_vel_x-val ((m <RemapLocalGoalList>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader traj_utils-msg:remap_lg_vel_x-val is deprecated.  Use traj_utils-msg:remap_lg_vel_x instead.")
  (remap_lg_vel_x m))

(cl:ensure-generic-function 'remap_lg_vel_y-val :lambda-list '(m))
(cl:defmethod remap_lg_vel_y-val ((m <RemapLocalGoalList>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader traj_utils-msg:remap_lg_vel_y-val is deprecated.  Use traj_utils-msg:remap_lg_vel_y instead.")
  (remap_lg_vel_y m))

(cl:ensure-generic-function 'remap_lg_vel_z-val :lambda-list '(m))
(cl:defmethod remap_lg_vel_z-val ((m <RemapLocalGoalList>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader traj_utils-msg:remap_lg_vel_z-val is deprecated.  Use traj_utils-msg:remap_lg_vel_z instead.")
  (remap_lg_vel_z m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <RemapLocalGoalList>) ostream)
  "Serializes a message object of type '<RemapLocalGoalList>"
  (cl:let* ((signed (cl:slot-value msg 'guard_drone_id)) (unsigned (cl:if (cl:< signed 0) (cl:+ signed 65536) signed)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) unsigned) ostream)
    )
  (cl:let ((__ros_arr_len (cl:length (cl:slot-value msg 'assignment))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_arr_len) ostream))
  (cl:map cl:nil #'(cl:lambda (ele) (cl:write-byte (cl:ldb (cl:byte 8 0) ele) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 8) ele) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 16) ele) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 24) ele) ostream))
   (cl:slot-value msg 'assignment))
  (cl:let ((__ros_arr_len (cl:length (cl:slot-value msg 'remap_lg_pos_x))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_arr_len) ostream))
  (cl:map cl:nil #'(cl:lambda (ele) (cl:let ((bits (roslisp-utils:encode-single-float-bits ele)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream)))
   (cl:slot-value msg 'remap_lg_pos_x))
  (cl:let ((__ros_arr_len (cl:length (cl:slot-value msg 'remap_lg_pos_y))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_arr_len) ostream))
  (cl:map cl:nil #'(cl:lambda (ele) (cl:let ((bits (roslisp-utils:encode-single-float-bits ele)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream)))
   (cl:slot-value msg 'remap_lg_pos_y))
  (cl:let ((__ros_arr_len (cl:length (cl:slot-value msg 'remap_lg_pos_z))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_arr_len) ostream))
  (cl:map cl:nil #'(cl:lambda (ele) (cl:let ((bits (roslisp-utils:encode-single-float-bits ele)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream)))
   (cl:slot-value msg 'remap_lg_pos_z))
  (cl:let ((__ros_arr_len (cl:length (cl:slot-value msg 'remap_lg_vel_x))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_arr_len) ostream))
  (cl:map cl:nil #'(cl:lambda (ele) (cl:let ((bits (roslisp-utils:encode-single-float-bits ele)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream)))
   (cl:slot-value msg 'remap_lg_vel_x))
  (cl:let ((__ros_arr_len (cl:length (cl:slot-value msg 'remap_lg_vel_y))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_arr_len) ostream))
  (cl:map cl:nil #'(cl:lambda (ele) (cl:let ((bits (roslisp-utils:encode-single-float-bits ele)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream)))
   (cl:slot-value msg 'remap_lg_vel_y))
  (cl:let ((__ros_arr_len (cl:length (cl:slot-value msg 'remap_lg_vel_z))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_arr_len) ostream))
  (cl:map cl:nil #'(cl:lambda (ele) (cl:let ((bits (roslisp-utils:encode-single-float-bits ele)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream)))
   (cl:slot-value msg 'remap_lg_vel_z))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <RemapLocalGoalList>) istream)
  "Deserializes a message object of type '<RemapLocalGoalList>"
    (cl:let ((unsigned 0))
      (cl:setf (cl:ldb (cl:byte 8 0) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) unsigned) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'guard_drone_id) (cl:if (cl:< unsigned 32768) unsigned (cl:- unsigned 65536))))
  (cl:let ((__ros_arr_len 0))
    (cl:setf (cl:ldb (cl:byte 8 0) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) __ros_arr_len) (cl:read-byte istream))
  (cl:setf (cl:slot-value msg 'assignment) (cl:make-array __ros_arr_len))
  (cl:let ((vals (cl:slot-value msg 'assignment)))
    (cl:dotimes (i __ros_arr_len)
    (cl:setf (cl:ldb (cl:byte 8 0) (cl:aref vals i)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) (cl:aref vals i)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) (cl:aref vals i)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) (cl:aref vals i)) (cl:read-byte istream)))))
  (cl:let ((__ros_arr_len 0))
    (cl:setf (cl:ldb (cl:byte 8 0) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) __ros_arr_len) (cl:read-byte istream))
  (cl:setf (cl:slot-value msg 'remap_lg_pos_x) (cl:make-array __ros_arr_len))
  (cl:let ((vals (cl:slot-value msg 'remap_lg_pos_x)))
    (cl:dotimes (i __ros_arr_len)
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
    (cl:setf (cl:aref vals i) (roslisp-utils:decode-single-float-bits bits))))))
  (cl:let ((__ros_arr_len 0))
    (cl:setf (cl:ldb (cl:byte 8 0) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) __ros_arr_len) (cl:read-byte istream))
  (cl:setf (cl:slot-value msg 'remap_lg_pos_y) (cl:make-array __ros_arr_len))
  (cl:let ((vals (cl:slot-value msg 'remap_lg_pos_y)))
    (cl:dotimes (i __ros_arr_len)
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
    (cl:setf (cl:aref vals i) (roslisp-utils:decode-single-float-bits bits))))))
  (cl:let ((__ros_arr_len 0))
    (cl:setf (cl:ldb (cl:byte 8 0) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) __ros_arr_len) (cl:read-byte istream))
  (cl:setf (cl:slot-value msg 'remap_lg_pos_z) (cl:make-array __ros_arr_len))
  (cl:let ((vals (cl:slot-value msg 'remap_lg_pos_z)))
    (cl:dotimes (i __ros_arr_len)
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
    (cl:setf (cl:aref vals i) (roslisp-utils:decode-single-float-bits bits))))))
  (cl:let ((__ros_arr_len 0))
    (cl:setf (cl:ldb (cl:byte 8 0) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) __ros_arr_len) (cl:read-byte istream))
  (cl:setf (cl:slot-value msg 'remap_lg_vel_x) (cl:make-array __ros_arr_len))
  (cl:let ((vals (cl:slot-value msg 'remap_lg_vel_x)))
    (cl:dotimes (i __ros_arr_len)
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
    (cl:setf (cl:aref vals i) (roslisp-utils:decode-single-float-bits bits))))))
  (cl:let ((__ros_arr_len 0))
    (cl:setf (cl:ldb (cl:byte 8 0) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) __ros_arr_len) (cl:read-byte istream))
  (cl:setf (cl:slot-value msg 'remap_lg_vel_y) (cl:make-array __ros_arr_len))
  (cl:let ((vals (cl:slot-value msg 'remap_lg_vel_y)))
    (cl:dotimes (i __ros_arr_len)
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
    (cl:setf (cl:aref vals i) (roslisp-utils:decode-single-float-bits bits))))))
  (cl:let ((__ros_arr_len 0))
    (cl:setf (cl:ldb (cl:byte 8 0) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) __ros_arr_len) (cl:read-byte istream))
  (cl:setf (cl:slot-value msg 'remap_lg_vel_z) (cl:make-array __ros_arr_len))
  (cl:let ((vals (cl:slot-value msg 'remap_lg_vel_z)))
    (cl:dotimes (i __ros_arr_len)
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
    (cl:setf (cl:aref vals i) (roslisp-utils:decode-single-float-bits bits))))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<RemapLocalGoalList>)))
  "Returns string type for a message object of type '<RemapLocalGoalList>"
  "traj_utils/RemapLocalGoalList")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'RemapLocalGoalList)))
  "Returns string type for a message object of type 'RemapLocalGoalList"
  "traj_utils/RemapLocalGoalList")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<RemapLocalGoalList>)))
  "Returns md5sum for a message object of type '<RemapLocalGoalList>"
  "94d1962f185de6a5a18e3c7557706328")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'RemapLocalGoalList)))
  "Returns md5sum for a message object of type 'RemapLocalGoalList"
  "94d1962f185de6a5a18e3c7557706328")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<RemapLocalGoalList>)))
  "Returns full string definition for message of type '<RemapLocalGoalList>"
  (cl:format cl:nil "int16 guard_drone_id~%~%uint32[] assignment~%~%float32[] remap_lg_pos_x~%float32[] remap_lg_pos_y~%float32[] remap_lg_pos_z~%~%float32[] remap_lg_vel_x~%float32[] remap_lg_vel_y~%float32[] remap_lg_vel_z~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'RemapLocalGoalList)))
  "Returns full string definition for message of type 'RemapLocalGoalList"
  (cl:format cl:nil "int16 guard_drone_id~%~%uint32[] assignment~%~%float32[] remap_lg_pos_x~%float32[] remap_lg_pos_y~%float32[] remap_lg_pos_z~%~%float32[] remap_lg_vel_x~%float32[] remap_lg_vel_y~%float32[] remap_lg_vel_z~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <RemapLocalGoalList>))
  (cl:+ 0
     2
     4 (cl:reduce #'cl:+ (cl:slot-value msg 'assignment) :key #'(cl:lambda (ele) (cl:declare (cl:ignorable ele)) (cl:+ 4)))
     4 (cl:reduce #'cl:+ (cl:slot-value msg 'remap_lg_pos_x) :key #'(cl:lambda (ele) (cl:declare (cl:ignorable ele)) (cl:+ 4)))
     4 (cl:reduce #'cl:+ (cl:slot-value msg 'remap_lg_pos_y) :key #'(cl:lambda (ele) (cl:declare (cl:ignorable ele)) (cl:+ 4)))
     4 (cl:reduce #'cl:+ (cl:slot-value msg 'remap_lg_pos_z) :key #'(cl:lambda (ele) (cl:declare (cl:ignorable ele)) (cl:+ 4)))
     4 (cl:reduce #'cl:+ (cl:slot-value msg 'remap_lg_vel_x) :key #'(cl:lambda (ele) (cl:declare (cl:ignorable ele)) (cl:+ 4)))
     4 (cl:reduce #'cl:+ (cl:slot-value msg 'remap_lg_vel_y) :key #'(cl:lambda (ele) (cl:declare (cl:ignorable ele)) (cl:+ 4)))
     4 (cl:reduce #'cl:+ (cl:slot-value msg 'remap_lg_vel_z) :key #'(cl:lambda (ele) (cl:declare (cl:ignorable ele)) (cl:+ 4)))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <RemapLocalGoalList>))
  "Converts a ROS message object to a list"
  (cl:list 'RemapLocalGoalList
    (cl:cons ':guard_drone_id (guard_drone_id msg))
    (cl:cons ':assignment (assignment msg))
    (cl:cons ':remap_lg_pos_x (remap_lg_pos_x msg))
    (cl:cons ':remap_lg_pos_y (remap_lg_pos_y msg))
    (cl:cons ':remap_lg_pos_z (remap_lg_pos_z msg))
    (cl:cons ':remap_lg_vel_x (remap_lg_vel_x msg))
    (cl:cons ':remap_lg_vel_y (remap_lg_vel_y msg))
    (cl:cons ':remap_lg_vel_z (remap_lg_vel_z msg))
))
