// Generated by gencpp from file traj_utils/GlbObsRcv.msg
// DO NOT EDIT!


#ifndef TRAJ_UTILS_MESSAGE_GLBOBSRCV_H
#define TRAJ_UTILS_MESSAGE_GLBOBSRCV_H

#include <ros/service_traits.h>


#include <traj_utils/GlbObsRcvRequest.h>
#include <traj_utils/GlbObsRcvResponse.h>


namespace traj_utils
{

struct GlbObsRcv
{

typedef GlbObsRcvRequest Request;
typedef GlbObsRcvResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GlbObsRcv
} // namespace traj_utils


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::traj_utils::GlbObsRcv > {
  static const char* value()
  {
    return "7f352b44c251978f0843cd60887550cf";
  }

  static const char* value(const ::traj_utils::GlbObsRcv&) { return value(); }
};

template<>
struct DataType< ::traj_utils::GlbObsRcv > {
  static const char* value()
  {
    return "traj_utils/GlbObsRcv";
  }

  static const char* value(const ::traj_utils::GlbObsRcv&) { return value(); }
};


// service_traits::MD5Sum< ::traj_utils::GlbObsRcvRequest> should match
// service_traits::MD5Sum< ::traj_utils::GlbObsRcv >
template<>
struct MD5Sum< ::traj_utils::GlbObsRcvRequest>
{
  static const char* value()
  {
    return MD5Sum< ::traj_utils::GlbObsRcv >::value();
  }
  static const char* value(const ::traj_utils::GlbObsRcvRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::traj_utils::GlbObsRcvRequest> should match
// service_traits::DataType< ::traj_utils::GlbObsRcv >
template<>
struct DataType< ::traj_utils::GlbObsRcvRequest>
{
  static const char* value()
  {
    return DataType< ::traj_utils::GlbObsRcv >::value();
  }
  static const char* value(const ::traj_utils::GlbObsRcvRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::traj_utils::GlbObsRcvResponse> should match
// service_traits::MD5Sum< ::traj_utils::GlbObsRcv >
template<>
struct MD5Sum< ::traj_utils::GlbObsRcvResponse>
{
  static const char* value()
  {
    return MD5Sum< ::traj_utils::GlbObsRcv >::value();
  }
  static const char* value(const ::traj_utils::GlbObsRcvResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::traj_utils::GlbObsRcvResponse> should match
// service_traits::DataType< ::traj_utils::GlbObsRcv >
template<>
struct DataType< ::traj_utils::GlbObsRcvResponse>
{
  static const char* value()
  {
    return DataType< ::traj_utils::GlbObsRcv >::value();
  }
  static const char* value(const ::traj_utils::GlbObsRcvResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TRAJ_UTILS_MESSAGE_GLBOBSRCV_H
