# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from traj_utils/LocalGoal.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class LocalGoal(genpy.Message):
  _md5sum = "a8f0ef3ec042e7d8948442e97ca38913"
  _type = "traj_utils/LocalGoal"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """int16 drone_id
int16 global_traj_id

float32 lg_pos_x
float32 lg_pos_y
float32 lg_pos_z

float32 lg_vel_x
float32 lg_vel_y
float32 lg_vel_z
"""
  __slots__ = ['drone_id','global_traj_id','lg_pos_x','lg_pos_y','lg_pos_z','lg_vel_x','lg_vel_y','lg_vel_z']
  _slot_types = ['int16','int16','float32','float32','float32','float32','float32','float32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       drone_id,global_traj_id,lg_pos_x,lg_pos_y,lg_pos_z,lg_vel_x,lg_vel_y,lg_vel_z

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(LocalGoal, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.drone_id is None:
        self.drone_id = 0
      if self.global_traj_id is None:
        self.global_traj_id = 0
      if self.lg_pos_x is None:
        self.lg_pos_x = 0.
      if self.lg_pos_y is None:
        self.lg_pos_y = 0.
      if self.lg_pos_z is None:
        self.lg_pos_z = 0.
      if self.lg_vel_x is None:
        self.lg_vel_x = 0.
      if self.lg_vel_y is None:
        self.lg_vel_y = 0.
      if self.lg_vel_z is None:
        self.lg_vel_z = 0.
    else:
      self.drone_id = 0
      self.global_traj_id = 0
      self.lg_pos_x = 0.
      self.lg_pos_y = 0.
      self.lg_pos_z = 0.
      self.lg_vel_x = 0.
      self.lg_vel_y = 0.
      self.lg_vel_z = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_2h6f().pack(_x.drone_id, _x.global_traj_id, _x.lg_pos_x, _x.lg_pos_y, _x.lg_pos_z, _x.lg_vel_x, _x.lg_vel_y, _x.lg_vel_z))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 28
      (_x.drone_id, _x.global_traj_id, _x.lg_pos_x, _x.lg_pos_y, _x.lg_pos_z, _x.lg_vel_x, _x.lg_vel_y, _x.lg_vel_z,) = _get_struct_2h6f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_2h6f().pack(_x.drone_id, _x.global_traj_id, _x.lg_pos_x, _x.lg_pos_y, _x.lg_pos_z, _x.lg_vel_x, _x.lg_vel_y, _x.lg_vel_z))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 28
      (_x.drone_id, _x.global_traj_id, _x.lg_pos_x, _x.lg_pos_y, _x.lg_pos_z, _x.lg_vel_x, _x.lg_vel_y, _x.lg_vel_z,) = _get_struct_2h6f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_2h6f = None
def _get_struct_2h6f():
    global _struct_2h6f
    if _struct_2h6f is None:
        _struct_2h6f = struct.Struct("<2h6f")
    return _struct_2h6f
